# Generated by Django 6.0.4 on 2026-04-22 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('public_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.RenameField(
            model_name='chatsession',
            old_name='start_time',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='end_time',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_user2', to=settings.AUTH_USER_MODEL),
        ),
    ]
